at3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reqs/', include('reqs.urls', namespace='reqs')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^contract/', include('contract.urls', namespace='contract')),
    url(r'^outage/', include('outage.urls', namespace='outage')),
    url(r'^po/', include('po.urls', namespace='po')),
    url(r'^vendor/', include('vendor.urls', namespace='vendor')),
    url(r'', include('tracker.urls', namespace='tracker')),
]

outage/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^setup/$', views.setup, name='setup'),
    url(r'^importd/$', views.load_x, name='importd'),
    url(r'^out_det/(?P<o_id>\d+)/$', views.outage_detail, name='outage_detail'),
    url(r'^new-outage/$', views.new_outage, name='new_outage'),
    url(r'^e-out/(?P<o_id>\d+)/$', views.edit_outage, name='edit_outage'),
    url(r'^out_csv_dump/$', views.out_csv_dump, name='out_csv_dump'),
    #homepage
    url(r'^$', views.dash, name='dash'),

]

po/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^add-po/$', views.add_po, name='add_po'),
    url(r'^edit-po/(?P<po_id>\d+)/$', views.edit_po, name='edit_po'),
    url(r'^al/(?P<po_id>\d+)/$', views.add_line, name='add_line'),
    url(r'^el/(?P<ln_id>\d+)/$', views.edit_line, name='edit_line'),
    url(r'^(?P<po_id>\d+)/$', views.po_detail, name='po_detail'),
    url(r'^by-vendor/(?P<v_id>\d+)/$', views.po_by_vendor, name='po_by_vendor'),
    url(r'^add-to-vendor/(?P<v_id>\d+)/$', views.add_po_to_vendor, name='add_po_to_vendor'),
    url(r'^$', views.po_home, name='po_home'),
]

outage/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Environment(models.Model):
    name = models.TextField()
    prod = models.BooleanField(default=False)
    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.TextField()
    def __str__(self):
        return self.name

class Severity(models.Model):
    name = models.TextField()
    value = models.IntegerField()
    def __str__(self):
        return self.name

class Outage(models.Model):
    description = models.TextField(null=True)
    environ = models.ForeignKey(Environment)
    service = models.ForeignKey(Service)
    sev = models.ForeignKey(Severity)
    began = models.DateTimeField(null=True)
    detected = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)
    tz = models.CharField(max_length=3)
    owner = models.TextField(null=True, blank=True)
    auth_owner = models.ForeignKey(User, related_name='owner', null=True)
    rca = models.TextField(null=True)
    status = models.TextField(null=True, blank=True)
    def __str__(self):
        return self.description

outage/forms.py
from django import forms

from .models import Outage

class OutageForm(forms.ModelForm):
    class Meta:
        model = Outage
        fields = ['description', 'environ', 'service', 'sev', 'began', 'detected', 'end', 'tz', 'auth_owner', 'rca', 'status']
        labels = {'description': 'Name of Outage', 'environ': 'Environment', 'service': 'Service Affected',
                    'sev': 'Severity', 'began': 'Time Outage Began', 'detected': 'Time Outage Was Detected', 'end': 'Time Outage Ended',
                    'tz': 'Timezone (XXX)', 'owner': 'Resolution Owner', 'rca': 'Root Cause Analysis', 'status': 'Outage Status'}

outage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
import import_data
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import time

# Create your views here.
from .models import Environment, Service, Severity, Outage
from .forms import OutageForm

def outage_detail(request, o_id):
    out = Outage.objects.get(id=o_id)
    context = {'out': out}
    return render(request, 'outage/out_detail.html', context)

def setup(request):
    prod_env = ('RMM', 'Continuity', 'HelpDesk', 'NOC', 'SOC')
    non_prod_env = ('Boston', 'Cranberry (non-HelpDesk)', 'Houston', 'Mumbai (non-NOC)', 'Pune (non-SOC)', 'London', 'Sydney')
    serv = ('Internet', 'Firewall', 'VPN', 'Wifi', 'Phones', 'Conference Room', 'VMware Engineering Environment', 'Applications')
    sev = (('Production Outage', 1), ('Production Degraded', 2), ('Non-Production Outage', 3), ('Non-Production Degraded', 4), ('Redundant Service Outage or Degregation', 5))
    e = Environment.objects.all()
    e.delete()
    s = Service.objects.all()
    s.delete()
    s = Severity.objects.all()
    s.delete()
    for x in prod_env:
        e = Environment(name=x, prod=True)
        e.save()
    for x in non_prod_env:
        e = Environment(name=x, prod=False)
        e.save()
    for x in serv:
        s = Service(name=x)
        s.save()
    for x in sev:
        s = Severity(name=x[0], value=int(x[1]))
        s.save()

    return HttpResponseRedirect(reverse('outage:dash'))

def load_x(request):
    de = Outage.objects.all()
    de.delete()
    d = import_data.d()
    for r in d:
        env = Environment.objects.get(name=r[1])
        serv = Service.objects.get(name=r[2])
        sev = Severity.objects.get(value=int(r[10]))
        o = Outage(description=r[0], environ=env, service=serv, sev=sev, began=r[3], detected=r[4], end=r[5]
                   , tz=r[6], owner=r[14], rca=r[15], status='Resolved')
        o.save()
    return HttpResponseRedirect(reverse('outage:dash'))

def dash(request):
    o = Outage.objects.order_by('-began')
    context = {'outage': o}
    return render(request, 'outage/dash.html', context)

@login_required(login_url='/users/login/')
def new_outage(request):
    if request.method != 'POST':
        date =  time.strftime("%Y-%m-%d")
        now_test = timezone.now()
        u = request.user
        form = OutageForm(initial = {'detected': now_test, 'auth_owner': u})
    else:
        form = OutageForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('outage:dash'))
    context = {'form': form}
    return render(request, 'outage/new_outage.html', context)

@login_required(login_url='/users/login/')
def edit_outage(request, o_id):
    if request.method != 'POST':
        track = Outage.objects.get(id=o_id)
        form = OutageForm(instance=track)
    else:
        track = Outage.objects.get(id=o_id)
        form = OutageForm(request.POST, instance=track)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('outage:outage_detail', args=[o_id]))
    context = {'form' : form, 'o_id' : o_id}
    return render(request, 'tracker/edit_outage.html', context)

def out_csv_dump(request):
    track = Outage.objects.all()
    csv_dump = open('csv_dump.csv', 'w')
    csv_dump.write('Description,Environment,Service,Severity,Began,Ended,TimeZone\n')
    for t in track:
        csv_dump.write(t.description+','
                    +t.environ.name+','
                    +t.service.name+','
                    +str(t.sev.value)+','
                    +t.began.strftime('%m/%d/%Y %H:%M:%S')+','
                    +t.end.strftime('%m/%d/%Y %H:%M:%S')+','
                    +t.tz+','
                    +'\n')
    csv_dump.close()
    csv_dump = open('csv_dump.csv', 'r')
    response = HttpResponse(csv_dump, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="out_csv_dump.csv"'
    return response

outage/templates/outage/dash.html
{% extends "tracker/topbar.html" %}

{% block content %}

<h1>Outages:</h1>
<hr>
<ul class="nav nav-pills text-right">
  <li><a href="{% url 'outage:new_outage' %}" class="btn btn-default">Add Outage <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></li>
  <li><a href="{% url 'outage:out_csv_dump' %}" class="btn btn-default">Export Records <span class="glyphicon glyphicon-download" aria-hidden="true"></span></a></li>
</ul>
<p></p>
<table class="table">
  <tr>
    <th>Description</th>
    <th>Severity</th>
    <th>Date</th>
    <th>Status</th>
  </tr>
  {% for o in outage %}
  <tr>
  <td><a href="{% url 'outage:outage_detail' o.id %}">{{o.description}}</a></td>
    <td>{{o.sev.name}}</td>
    <td>{{o.began}}</td>
    <td>{{o.status}}</td>
  </tr>
  {% empty %}
  <tr>
    <td>No Outages</td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

outage/templates/outage/edit_outage.html
{% extends "tracker/topbar.html" %}
{% load bootstrap3 %}

{% block content %}
<form class="form" action="{% url 'outage:edit_outage' o_id %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>

{% endblock content %}

outage/templates/outage/new_outage.html
{% extends "tracker/topbar.html" %}
{% load bootstrap3 %}

{% block content %}
<form class="form" action="{% url 'outage:new_outage' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>

{% endblock content %}

outage/templates/outage/out_detail.html
{% extends "tracker/topbar.html" %}

{% block content %}
<h1 class="text-uppercase">{{out.description}}</h1>
<div>
<ul class="nav nav-pills nav-justified">
  <li> </li>
  <li> </li>
  <li> </li>
  <li><a class="btn btn-default" href="{% url 'outage:edit_outage' out.id %}" role="button">Edit Outage <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></li>
  {% if request.user.is_superuser or request.user == t.proc_owner or request.user == t.business_owner %}
  <li><a class="btn btn-danger" href="" role="button">Delete Record <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></li>
  {% endif %}
</ul>
</div>
<hr>
<div class="container-fluid text-center">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title"<strong>Status: </strong></div>
      </div>
      <div class="panel-body">
          {{out.status}}
      </div>
    </div>
  </div>
    <div class="row">
        <div class="col-md-6 well well-sm"><h4><strong>Began: </strong>{{out.began}}</h4></div>
        <div class="col-md-6 well well-sm"><h4><strong>Ended: </strong>{{out.end}}</h4></div>
        <div class="col-md-6 well well-sm"><h4><strong>Detected: </strong>{{out.detected}}</h4></div>
        <div class="col-md-6 well well-sm"><h4><strong>Owner: </strong>{{out.auth_owner.first_name}} {{out.auth_owner.last_name}}</h4></div>
    </div>

  <hr>
    <div class="row well text-center">
      <div class="row">
        <div class="col-md-6"><strong>Environment: </strong>{{out.environ.name}}</div>
        <div class="col-md-6"><strong>Production?: </strong>{{out.environ.prod}}</div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-6"><strong>Service: </strong>{{out.service.name}}</div>
        <div class="col-md-6"><strong>Severity: </strong>{{out.sev.value}}</div>
      </div>
    </div>
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title"<strong>RCA: </strong></div>
        </div>
        <div class="panel-body">
            {{out.rca}}
        </div>
      </div>
    </div>
</div>

{% endblock content %}

outage/templates/outage/out_detail_old.html
{% extends "tracker/topbar.html" %}

{% block content %}

<h1>{{out.description}}</h1>
<h1><small>{{out.status}}</small></h1>
<a class="btn btn-default" href="{% url 'outage:edit_outage' out.id %}" role="button">Edit Outage <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>

<div class="container-fluid text-center">
<div class="row ">
<div class="col-md-3 panel panel-default">Environment: {{out.environ.name}}</div>
<div class="col-md-3 panel panel-default">Production?{{out.environ.prod}}</div>
<div class="col-md-3 panel panel-default">Service: {{out.service.name}}</div>
<div class="col-md-3 panel panel-default">Severity: {{out.sev.value}}</div>
</div>
<p> </p>
<div class="row">
<div class="col-md-3 panel panel-default">Began: {{out.began}}</div>
<div class="col-md-3 panel panel-default">Detected: {{out.detected}}</div>
<div class="col-md-3 panel panel-default">End: {{out.end}}</div>
<div class="col-md-3 panel panel-default">Timezone: {{out.tz}}</div>
</div>
<p> </p>
<div class="row">
<div class="col-md-12 panel panel-default">Owner: {{out.owner}}</div>
</div>
<div class="row">
<div class="col-md-12 panel panel-default">RCA: {{out.rca}}</div>
</div>
</div>


{% endblock content %}