at3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reqs/', include('reqs.urls', namespace='reqs')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^contract/', include('contract.urls', namespace='contract')),
    url(r'^outage/', include('outage.urls', namespace='outage')),
    url(r'^po/', include('po.urls', namespace='po')),
    url(r'^vendor/', include('vendor.urls', namespace='vendor')),
    url(r'', include('tracker.urls', namespace='tracker')),
]

po/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^add-po/$', views.add_po, name='add_po'),
    url(r'^edit-po/(?P<po_id>\d+)/$', views.edit_po, name='edit_po'),
    url(r'^al/(?P<po_id>\d+)/$', views.add_line, name='add_line'),
    url(r'^el/(?P<ln_id>\d+)/$', views.edit_line, name='edit_line'),
    url(r'^(?P<po_id>\d+)/$', views.po_detail, name='po_detail'),
    url(r'^by-vendor/(?P<v_id>\d+)/$', views.po_by_vendor, name='po_by_vendor'),
    url(r'^add-to-vendor/(?P<v_id>\d+)/$', views.add_po_to_vendor, name='add_po_to_vendor'),
    url(r'^$', views.po_home, name='po_home'),
]

reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^rehome/atcsvdump/$', views.at_csv_dump, name='at_csv_dump'),
    url(r'^rehome/gtest/$', views.graphos_test, name='graphos_test'),
    url(r'^rehome/$', views.home, name='home'),
]

reports/models.py
from django.db import models

# Create your models here.

class Historical(models.Model):
    date = models.DateField(auto_now_add=True)
    key = models.CharField(max_length=140)
    value = models.DecimalField(max_digits=19, decimal_places = 5)
    def  __str__(self):
        return str(self.key) + str(self.date)

reports/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from tracker.models import Tracker, Finance
from django.core.urlresolvers import reverse
from datetime import datetime, date
from reports.models import Historical
from graphos.sources.model import ModelDataSource, SimpleDataSource
from graphos.renderers.gchart import LineChart, GaugeChart

# Create your views here.

def home(request):
    #grab all data
    data = Tracker.objects.all()
    #grab data filed to open items
    open = Tracker.objects.filter(end_date__isnull=True)
    acount = 0.0
    asum = 0.0
    cat_sum_dict = {}
    cat_count_dict = {}
    #run through open items and calculate averages
    for t in open:
        ed = date.today()
        sd = t.start_date
        day  = ed - sd
        acount = acount + 1
        asum = asum + day.days
        #make sure the key exists in the dictionary
        if t.type in cat_sum_dict:
            a = 1 + 1
        else:
            cat_sum_dict[t.type] = 0.0
        #make sure the key exists in the dictionary
        if t.type in cat_count_dict:
            b = 1 + 1
        else:
            cat_count_dict[t.type] = 0.0
        #write the intances data to the dictionary
        cat_sum_dict[t.type] = cat_sum_dict[t.type] + day.days
        cat_count_dict[t.type] = cat_count_dict[t.type] + 1
    #cacluate all average
    all_average = asum / acount

    #calcualte avg by category
    cat_avg = {}
    for cat in cat_sum_dict.keys():
        avg = cat_sum_dict[cat] / cat_count_dict[cat]
        cat_avg[cat] = avg
    data = [['Label', 'Value'], ['Days', int(all_average)]]
    if int(all_average) > 14:
        gmax = int(all_average)
    else:
        gmax = 14
    speed_data = SimpleDataSource(data=data)
    speed_chart = GaugeChart(speed_data, width=400, height=200, options={
        'greenFrom': 0, 'greenTo': 5, 'yellowFrom': 5, 'yellowTo': 7, 'redFrom': 7, 'redTo': gmax, 'max': gmax})

    context = {'data': data, 'all_average': all_average, 'cat_avg': cat_avg, 'chart': speed_chart}
    return render(request, 'reports/home.html', context)


def at_csv_dump(request):
    track = Tracker.objects.all()
    csv_dump = open('csv_dump.csv', 'w')
    csv_dump.write('Initiative Name,Supplier,Type,Scope,Comments,StartDate,EndDate,BusinessOwner,SBU,ProcOwner,Category\n')
    for t in track:
        csv_dump.write(t.init_name+','+t.supplier+','+t.type.type+','+t.scope.scope+','+t.comments+','+str(t.start_date)+','+str(t.end_date)+','+t.business_owner.first_name+t.business_owner.last_name+','+t.division.division+','+t.proc_owner.first_name+t.proc_owner.last_name+','+t.category.category+'\n')
    csv_dump.close()
    csv_dump = open('csv_dump.csv', 'r')
    response = HttpResponse(csv_dump, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="at_csv_dump.csv"'
    return response

def activity_grid(request, user):
    return render(request, 'reports/home.html')

def graphos_test(request):
    #q = Tracker.objects.all()
    #data_source = ModelDataSource(q, fields = ['type', 'contract_value'])
    data = [['Year', 'Sales'],
            [2010, 150],
            [2011, 200],
            [2012, 300],
            ]
    data_source = SimpleDataSource(data=data)
    chart = LineChart(data_source)
    context = {'chart': chart}
    return render(request, 'reports/g_test.html', context)

def act_by_type(request):
    return render(request, 'reports/placeholder.html')

def act_by_owner(request):
    return render(request, 'reports/placeholder.html')

def act_by_cat(request):
    return render(request, 'reports/placeholder.html')

def wrkdys_complete(request):
    return render(request, 'reports/placeholder.html')

def act_by_month(request):
    return render(request, 'reports/placeholder.html')

def act_by_sbu(request):
    return render(request, 'reports/placeholder.html')

reports/templates/reports/g_test.html
{% extends "tracker/topbar.html" %}
{% block content %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
</script>
{{ chart.as_html }}
{% endblock content %}

reports/templates/reports/home.html
{% extends "tracker/topbar.html" %}

{% block content %}

<div class="container-fluid text-center">
  <div class="text-center">
    <center>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["gauge"]});
    </script>
    {{ chart.as_html }}
  </center>
  </div>
  <h3>Average Pending Items Days Open</h3>
  <div>
    <table class="table table-bordered table-hover">
      <tr>
        <th class="text-center">Category</th>
        <th class="text-center">Average Days Outstanding</th>
      </tr>
      {% for c, v in cat_avg.items %}
      <tr>
        <td>{{ c }}</td>
        <td>{{ v }}</td>
      </tr>
      {% empty %}
      <p>No data</p>
      {% endfor %}
    </table>
  </div
</div>
<hr>
<div class="row">
    <a href="{% url 'reports:graphos_test' %}"><div class="col-md-4"><button type="button" class="btn btn-default btn-block">Activities by Type</button></div></a>
    <div class="col-md-4"><button type="button" class="btn btn-default btn-block">Activities by Owner</button></div>
    <div class="col-md-4"><button type="button" class="btn btn-default btn-block">Activities by Category</button></div>
</div>
<div class="row">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">
    <div class="col-md-4"><button type="button" class="btn btn-default btn-block">Workdays to Complete</button></div>
    <div class="col-md-4"><button type="button" class="btn btn-default btn-block">Activites by Month</button></div>
    <div class="col-md-4"><button type="button" class="btn btn-default btn-block">Activities by SBU</button></div>
</div>
<div class="row">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">
    <div class="col-md-12"><button type="button" class="btn btn-primary btn-block">Activity Grid</button></div>
</div>
{% if request.user.is_superuser %}
<hr>
<div class="container-fluid text-center table-hover">
  <a href="{% url 'reports:at_csv_dump' %}" class="btn btn-default" role="button"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>  AT CSV Dump</a>
</div>
{% endif %}
{% endblock content %}

reports/templates/reports/placeholder.html
{% extends "tracker/topbar.html" %}
{% block content %}

{% endblock content %}