at3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reqs/', include('reqs.urls', namespace='reqs')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^contract/', include('contract.urls', namespace='contract')),
    url(r'^outage/', include('outage.urls', namespace='outage')),
    url(r'^po/', include('po.urls', namespace='po')),
    url(r'^vendor/', include('vendor.urls', namespace='vendor')),
    url(r'', include('tracker.urls', namespace='tracker')),
]

contract/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.recent_con, name='recent_con'),
]

outage/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^setup/$', views.setup, name='setup'),
    url(r'^importd/$', views.load_x, name='importd'),
    url(r'^out_det/(?P<o_id>\d+)/$', views.outage_detail, name='outage_detail'),
    url(r'^new-outage/$', views.new_outage, name='new_outage'),
    url(r'^e-out/(?P<o_id>\d+)/$', views.edit_outage, name='edit_outage'),
    url(r'^out_csv_dump/$', views.out_csv_dump, name='out_csv_dump'),
    #homepage
    url(r'^$', views.dash, name='dash'),

]

po/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^add-po/$', views.add_po, name='add_po'),
    url(r'^edit-po/(?P<po_id>\d+)/$', views.edit_po, name='edit_po'),
    url(r'^al/(?P<po_id>\d+)/$', views.add_line, name='add_line'),
    url(r'^el/(?P<ln_id>\d+)/$', views.edit_line, name='edit_line'),
    url(r'^(?P<po_id>\d+)/$', views.po_detail, name='po_detail'),
    url(r'^by-vendor/(?P<v_id>\d+)/$', views.po_by_vendor, name='po_by_vendor'),
    url(r'^add-to-vendor/(?P<v_id>\d+)/$', views.add_po_to_vendor, name='add_po_to_vendor'),
    url(r'^$', views.po_home, name='po_home'),
]

reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^rehome/atcsvdump/$', views.at_csv_dump, name='at_csv_dump'),
    url(r'^rehome/gtest/$', views.graphos_test, name='graphos_test'),
    url(r'^rehome/$', views.home, name='home'),
]

tracker/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^closed/$', views.closed, name='closed'),
    url(r'^reqs/$', views.reqs, name='reqs'),
    url(r'^t/(?P<track_id>\d+)/$', views.detail, name='detail'),
    url(r'^f/(?P<track_id>\d+)/$', views.detailf, name='detailf'),
    url(r'^et/(?P<track_id>\d+)/$', views.edittracker, name='edittracker'),
    url(r'^ef/(?P<fin_id>\d+)/$', views.editfinance, name='editfinance'),
    url(r'^ef/(?P<fin_id>\d+)/$', views.editfinance, name='editfinance'),
    url(r'^nf/(?P<track_id>\d+)/$', views.newfinance, name='newfinance'),
    url(r'^nt/$', views.newtracker, name='newtracker'),
    url(r'^dyrwtd/(?P<track_id>\d+)/$', views.chk_del, name='chk_del'),
    url(r'^fasdgalaksjdnfnfnf/(?P<track_id>\d+)/$', views.delete, name='delete'),
    #homepage
    url(r'^$', views.index, name='index'),

]

users/urls.py
#users urls

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    #logout
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

tracker/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=50)
    def __str__(self):
        return self.category

class SBU(models.Model):
    division = models.CharField(max_length=50)
    def __str__(self):
        return self.division

class Scope(models.Model):
    scope = models.CharField(max_length=50)
    def __str__(self):
        return self.scope

class Type(models.Model):
    type = models.CharField(max_length=50)
    def __str__(self):
        return self.type

class Tracker(models.Model):
    init_name = models.CharField(max_length=50)
    supplier = models.CharField(max_length=50, null=True, blank=True)
    type  = models.ForeignKey(Type)
    scope  = models.ForeignKey(Scope)
    comments = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    business_owner = models.ForeignKey(User, related_name='bus')
    division = models.ForeignKey(SBU)
    proc_owner = models.ForeignKey(User, related_name='proc', limit_choices_to={'groups': 2})
    category = models.ForeignKey(Category)
    contract_value = models.DecimalField(max_digits=10, decimal_places=2)
    theo = models.BooleanField(default=False)
    status = models.CharField(max_length=140)
    def __str__(self):
        return self.init_name

class Budget(models.Model):
    budget_type = models.CharField(max_length=50)
    def __str__(self):
        return self.budget_type

class CSType(models.Model):
    cs_type = models.CharField(max_length=50)
    def __str__(self):
        return self.cs_type

class Confidence(models.Model):
    confidence = models.CharField(max_length=50)
    def __str__(self):
        return self.confidence

class Finance(models.Model):
    record = models.ForeignKey(Tracker)
    term_mo = models.IntegerField()
    yr_savings = models.DecimalField(max_digits=10, decimal_places=2)
    spend_cur_fy = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    spend_prev_fy = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    contract_start = models.DateField()
    contract_end = models.DateField(null=True, blank=True)
    savings_start = models.DateField(null=True, blank=True)
    savings_end = models.DateField(null=True, blank=True)
    budget_type = models.ForeignKey(Budget, null=True, blank=True)
    cs_type = models.ForeignKey(CSType, null=True, blank=True)
    confidence = models.ForeignKey(Confidence, null=True, blank=True)
    nature = models.TextField()
    def __str__(self):
        return str(self.record) + ' ' + str(self.contract_start)

class TaskStatus(models.Model):
    name = models.TextField()
    def __str__(self):
        return self.name

class Task(models.Model):
    record = models.ForeignKey(Tracker)
    description = models.TextField()
    due = models.DateField(null=True, blank=True, auto_now=True)
    status = models.ForeignKey(TaskStatus)
    def __str__(self):
        return str(self.record.id) + " " + self.description

tracker/forms.py
from django import forms

from .models import Tracker, Finance, Task, TaskStatus

class TrackerForm(forms.ModelForm):
    class Meta:
        model = Tracker
        fields = ['init_name', 'supplier', 'type', 'scope', 'comments', 'theo', 'start_date', 'end_date', 'business_owner', 'division', 'proc_owner', 'category', 'contract_value', 'status']
        labels = {'init_name': 'Initiative Name', 'supplier': 'Supplier Name', 'type': 'Activity Type', 'scope': 'Activity Scope',
                  'comments': 'Comments', 'theo': 'Planned Project?', 'start_date': 'Activity Start Date (YYYY-MM-DD)', 'end_date': 'Activity End Date (YYYY-MM-DD)',
                  'business_owner': 'Business Owner', 'division': 'SBU', 'proc_owner': 'Procurement Owner', 'category': 'Category', 'contract_value': 'Total Contract Value', 'status': 'Status' }

class FinanceForm(forms.ModelForm):
    class Meta:
        model = Finance
        fields = ['record','term_mo', 'yr_savings', 'spend_cur_fy', 'spend_prev_fy', 'contract_start', 'contract_end',
                  'savings_start', 'savings_end', 'budget_type', 'cs_type', 'confidence', 'nature']
        labels = {'record': 'Tracker', 'term_mo': 'Term in Months', 'yr_savings': '12 mo Savings', 'spend_cur_fy': 'Current FY Spend', 'spend_prev_fy': 'Previous FY Spend', 'contract_start': 'Contract Start Date (YYYY-MM-DD)', 'contract_end': 'Contract End Date (YYYY-MM-DD)',
                  'savings_start': 'Savings Start Date (YYYY-MM-DD)', 'savings_end': 'Savings End Date (YYYY-MM-DD)', 'budget_type': 'Budget Type', 'cs_type': 'Cost Savings Type', 'confidence': 'Confidence Level', 'nature': 'Nature of Deal'}

class TaskForm(forms.Form):
    description = forms.CharField(max_length = 255, strip=True)
    due = forms.DateField()
    status = forms.ModelChoiceField(queryset=TaskStatus.objects.all())

tracker/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import Tracker, Finance, Task, TaskStatus
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import TrackerForm, FinanceForm, TaskForm
import time
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    context = 0
    warning = 0
    warn = 0
    usr = 0
    if request.user.is_authenticated():
        rec = Tracker.objects.filter(proc_owner=request.user, end_date__isnull=True).order_by('start_date')
        rec_list = {}
        for r in rec:
            try:
                f = Finance.objects.get(record=r)
            except:
                f = 0
                warn = warn + 1
            rec_list[r] = f

        if warn > 0:
            warning = 'finance'

        proj = Tracker.objects.filter(business_owner=request.user, end_date__isnull=True).order_by('start_date')

        if request.user.groups.filter(name='Procurement Owners').exists():
            usr = 'Proc'

        context = {'rec':rec_list, 'proj':proj, 'warning': warning, 'usr': usr}
    return render(request, 'tracker/index.html', context)

def closed(request):
    context = 0
    usr = 0
    rec_list = {}
    if request.user.is_authenticated():
        rec = Tracker.objects.filter(proc_owner=request.user, end_date__isnull=False).order_by('-end_date')
        for r in rec:
            try:
                f = Finance.objects.get(record=r)
            except:
                f = 0
            rec_list[r] = f

        proj = Tracker.objects.filter(business_owner=request.user, end_date__isnull=False).order_by('-end_date')

        if request.user.groups.filter(name='Procurement Owners').exists():
            usr = 'Proc'

        context = {'rec':rec_list, 'proj':proj, 'usr': usr}
    return render(request, 'tracker/index.html', context)

def reqs(request):
    return render(request, 'tracker/reqs.html')

def detail(request, track_id):
    #inline form handling
    if request.method == 'POST':
        form = TaskForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            obj = Task(record=Tracker.objects.get(id=track_id), description=data['description'], due=data['due'], status=data['status'])
            obj.save()
    else:
        form = TaskForm(initial={'status': TaskStatus.objects.get(name='Open')})

    #content
    t = Tracker.objects.get(id=track_id)
    try:
        f = Finance.objects.get(record=t)
    except:
        f = 0
    if t.contract_value == 0:
        fin = 'd'
    else:
        fin = 'n'
    tasks = Task.objects.filter(record=track_id)
    context = {'t':t, 'f':f, 'fin':fin, 'tasks': tasks, 'form':form}
    return render(request, 'tracker/detail.html', context)

def detailf(request, track_id):
    t = Tracker.objects.get(id=track_id)
    try:
        f = Finance.objects.get(record=t)
    except:
        f = 0
    context = {'t':t, 'f':f}
    return render(request, 'tracker/detailf.html', context)

@login_required(login_url='/users/login/')
def newtracker(request):
    if request.method != 'POST':
        date = time.strftime("%Y-%m-%d")
        u = request.user
        form = TrackerForm(initial = {'start_date': date, 'proc_owner': u})
    else:
        form = TrackerForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tracker:index'))
    context = {'form': form}
    return render(request, 'tracker/newtracker.html', context)

@login_required(login_url='/users/login/')
def newfinance(request, track_id):
    if request.method != 'POST':
        track = Tracker.objects.get(id=track_id)
        form = FinanceForm(initial={'record': track})
    else:
        form = FinanceForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tracker:index'))
    context = {'form': form, 'track_id': track_id}
    return render(request, 'tracker/newfin.html', context)

@login_required(login_url='/users/login/')
def edittracker(request, track_id):
    if request.method != 'POST':
        track = Tracker.objects.get(id=track_id)
        form = TrackerForm(instance=track)
    else:
        track = Tracker.objects.get(id=track_id)
        form = TrackerForm(request.POST, instance=track)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tracker:detail', args=[track_id]))
    context = {'form' : form, 'track_id' : track_id}
    return render(request, 'tracker/edittracker.html', context)

@login_required(login_url='/users/login/')
def editfinance(request, fin_id):
    if request.method != 'POST':
        fin = Tracker.objects.get(id=fin_id)
        form = TrackerForm(instance=fin)
    else:
        fin = Tracker.objects.get(id=fin_id)
        form = TrackerForm(request.POST, instance=fin)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tracker:index'))
    context = {'form' : form, 'fin_id' : fin_id}
    return render(request, 'tracker/editfin.html', context)

@login_required(login_url='/users/login/')
def chk_del(request, track_id):
    t = Tracker.objects.get(id=track_id)
    context = {'t':t, 'track_id': track_id}
    return render(request, 'tracker/chk_del.html', context)

@login_required(login_url='/users/login/')
def delete(request, track_id):
    t = Tracker.objects.get(id=track_id)
    try:
        f = Finance.objects.get(record=t)
        f.delete()
    except:
        f = 0
    t.delete()
    return HttpResponseRedirect(reverse('tracker:index'))

tracker/templates/tracker/chk_del.html
{% extends "tracker/topbar.html" %}

{% block content %}
<div class="container-fluid">
<h1 class="text-center">Do you really want to delete {{ t.init_name }}?  <small><p>You will never be able to recover it, but maybe after the heat death of the universe a new big bang will create a comparable universe where the exact pattern of bits that make up this record will be recreated.</p></small></h1>
</div>
<hr>
<ul class="nav nav-pills nav-justified">
<li><a class="btn btn-danger" href="{% url 'tracker:delete' t.id %}" role="button">Yes, I will never need this again!</a></li>
<li>                              </li>
<li><a class="btn btn-default" href="{% url 'tracker:detail' t.id %}" role="button">No! Save me!</a></li>
</ul>
{% endblock content %}

tracker/templates/tracker/detail.html
{% extends "tracker/topbar.html" %}
{% load bootstrap3 %}

{% block content %}
<h1 class="text-uppercase">{{ t.init_name }}</h1>
<div>
<ul class="nav nav-pills nav-justified">
  <li role="presentation" class="active"><a>Tracker</a></li>
  {% if fin == 'd' %}
  <li role="presentation" class="disabled"><a>Finance</a></li>
  {% elif fin == 'n' and f == 0 %}
  <li role="presentation"><a href="{% url 'tracker:newfinance' t.id %}">Finance</a></li>
  {% else %}
  <li role="presentation"><a href="{% url 'tracker:detailf' t.id %}">Finance</a></li>
  {% endif %}
  <li>       </li>
  <li><a class="btn btn-default" href="{% url 'tracker:edittracker' t.id %}" role="button">Edit Tracker <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></li>
  {% if request.user.is_superuser or request.user == t.proc_owner or request.user == t.business_owner %}
  <li><a class="btn btn-danger" href="{% url 'tracker:chk_del' t.id %}" role="button">Delete Record <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></li>
  {% endif %}
</ul>
</div>
<hr>
<div class="container-fluid text-center">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title"<strong>Status: </strong></div>
      </div>
      <div class="panel-body">
          {{ t.status }}
      </div>
    </div>
  </div>
    <div class="row">
        <div class="col-md-6 well well-sm"><h4><strong>Start Date: </strong>{{ t.start_date }}</h4></div>
        <div class="col-md-6 well well-sm"><h4><strong>End Date: </strong>{{ t.end_date }}</h4></div>
        <div class="col-md-6 well well-sm"><h4><strong>Business Owner: </strong>{{ t.business_owner.first_name }} {{ t.business_owner.last_name }}</h4></div>
        <div class="col-md-6 well well-sm"><h4><strong>Procurement Owner: </strong>{{ t.proc_owner.first_name }} {{ t.proc_owner.last_name }}</h4></div>
    </div>
    <div class="row">
      <div class="col-md-12"><h2>Contract Value: ${{ t.contract_value }}</h2></div>
    </div>
  <hr>
    <div class="row well text-center">
      <div class="row">
        <div class="col-md-4"><strong>Supplier: </strong>{{ t.supplier }}</div>
        <div class="col-md-4"><strong>Type: </strong>{{ t.type }}</div>
        <div class="col-md-4"><strong>Scope: </strong>{{ t.scope }}</div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-4"><strong>Division: </strong>{{ t.division }}</div>
        <div class="col-md-4"><strong>Category: </strong>{{ t.category }}</div>
        <div class="col-md-4"><strong>Theoretical: </strong>{{ t.theo }}</div>
      </div>
    </div>
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title"<strong>Comments: </strong></div>
        </div>
        <div class="panel-body">
            {{ t.comments }}
        </div>
      </div>
    </div>
</div>
<div class="container-fluid">
  Tasks:
  <table class="table">
    <tr>
      <th>Description</th>
      <th>Due Date</th>
      <th>Status</th>
      <th></th>
    </tr>
    {% for ta in tasks %}
    <tr>
      <td>{{ ta.description }}</td>
      <td>{{ ta.due }}</td>
      <td>{{ ta.status.name }}</td>
      <td><button name="submit" class="btn btn-primary"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button></td>
    </tr>
    {% empty %}
    <tr>
      <td>No Tasks</td>
    </tr>
    {% endfor %}
    <tr>
      <form class="form-inline" action="{% url 'tracker:detail' t.id %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <td>{{ form.description.errors}} {{ form.description }}</td>
        <td>{{ form.due.errors}} {{ form.due }}</td>
        <td>{{ form.status.errors}} {{ form.status }}</td>
        <td>
          {% buttons %}
          <button name="submit" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
          {% endbuttons %}
        </td>
      </form>
    </tr>
  </table>
</div>
{% endblock content %}

tracker/templates/tracker/editfin.html
{% extends "tracker/topbar.html" %}
{% load bootstrap3 %}

{% block content %}
<form class="form" action="{% url 'tracker:editfinance' fin_id %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>

{% endblock content %}

tracker/templates/tracker/index.html
{% extends "tracker/topbar.html" %}

{% block content %}
{% if usr == 'Proc' %}

  {% if warning == 'finance' %}
    <div class="alert alert-warning" role="alert"><strong>WARNING:</strong> You have records with non-zero contract values what do not have finance information.  Please correct this as it mandatory for several executive reports.</div>
  {% endif %}



<div>
  <h3>Your Tasks:</h3>
  <table class="table table-condensed table-hover">
    <tr>
      <th>Initiative Name</th>
      <th>Type</th>
      <th>Contract Value</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th></th>
    </tr>
    {% for r, f in rec.items %}
    {% if f == 0 and r.contract_value > 0 %}
      <tr class="warning">
    {% else %}
      <tr>
    {% endif %}
        <td style="vertical-align:middle"><a href="{% url 'tracker:detail' r.id %}">{{ r.init_name }}</a></td>
        <td style="vertical-align:middle">{{ r.type }}</td>
        <td style="vertical-align:middle">${{ r.contract_value }}</td>
        <td style="vertical-align:middle">{{ r.start_date }}</td>
        <td style="vertical-align:middle">{{ r.end_date }}</td>
        <td style="vertical-align:middle">{{ r.status }}</td>
        <td class="text-right">
          <a class="btn btn-default" href="{% url 'tracker:edittracker' r.id %}" role="button"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
          {% if f == 0 and r.contract_value > 0 %}
            <a class="btn btn-danger" href="{% url 'tracker:newfinance' r.id %}" role="button"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>
          {% elif r.contract_value > 0 %}
            <a class="btn btn-default" href="{% url 'tracker:editfinance' f.id %}" role="button"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>
          {% else %}
            <a class="btn btn-default disabled" role="button"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>
          {% endif %}
        </td>
      </tr>
    {% empty %}
    <tr>
      <td>No Records</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endif %}


<div>
  <h3>Managed Tasks:</h3>
  <table class="table table-condensed table-hover ">
    <tr>
      <th>Initiative Name</th>
      <th>Type</th>
      <th class=>Contract Value</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th></th>
    </tr>
    {% for p in proj %}
    <tr>
      <td style="vertical-align:middle"><a href="{% url 'tracker:detail' p.id %}">{{ p.init_name }}</a></td>
      <td style="vertical-align:middle">{{ p.type }}</td>
      <td style="vertical-align:middle">${{ p.contract_value }}</td>
      <td style="vertical-align:middle">{{ p.start_date }}</td>
      <td style="vertical-align:middle">{{ p.end_date }}</td>
      <td style="vertical-align:middle">{{ p.status }}</td>
      <td class="text-right"><a class="btn btn-default" href="#" role="button"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
        {% if f == 0 and p.contract_value > 0 %}
          <a class="btn btn-danger" href="{% url 'tracker:newfinance' p.id %}" role="button"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>
        {% else %}
          <a class="btn btn-default disabled" role="button"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>
        {% endif %}
      </td>
    </tr>
    {% empty %}
    <tr>
    <td>No Records</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    </tr>
    {% endfor %}
  </table>
</div>
<hr>
<div class="container-fluid text-center">
  <a href="{% url 'tracker:newtracker' %}" class="btn btn-default" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Activity</a>
  <a href="{% url 'reqs:reqs' %}" class="btn btn-default" role="button"><span class="glyphicon glyphicon-inbox" aria-hidden="true"></span> Requests</a>
</div>
{% endblock content %}

tracker/templates/tracker/topbar.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SPAT</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'tracker:index' %}">SPAT</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li class="dropdown">
              <a href="{% url 'tracker:reqs' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quick Actions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'vendor:add_vendor' %}">New Vendor</a></li>
                <li class="disabled"><a href="">New Quote</a></li>
                <li><a href="{% url 'po:add_po' %}">New PO</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'tracker:newtracker' %}">New Activity</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'outage:new_outage' %}">New Outage</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="">New Contract</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="{% url 'po:po_home' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Procurement<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'vendor:vendor_home' %}">Vendors</a></li>
                <li class="disabled"><a href="">Quotes</a></li>
                <li><a href="{% url 'po:po_home' %}">Purchase Orders</a></li>
              </ul>
            </li>


            <li class="disabled"><a href="{% url 'reports:home' %}">Reports</a></li>
            <li><a href="{% url 'contract:recent_con' %}">Contracts</a></li>
            <li><a href="{% url 'outage:dash' %}">Outages</a></li>


            <li><a href="{% url 'tracker:closed' %}">Closed Projects</a></li>
            {% if request.user.is_superuser %}
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            {% endif %}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li>
                <a>Hello, {{ user.first_name }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Register</a></li>
              <li><a href="{% url 'users:login' %}">Log In</a></li>
            {% endif %}
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div>
        {% block content %}{% endblock content %}
      </div>


    </div> <!-- /container -->
  </body>
</html>