at3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reqs/', include('reqs.urls', namespace='reqs')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^contract/', include('contract.urls', namespace='contract')),
    url(r'^outage/', include('outage.urls', namespace='outage')),
    url(r'^po/', include('po.urls', namespace='po')),
    url(r'^vendor/', include('vendor.urls', namespace='vendor')),
    url(r'', include('tracker.urls', namespace='tracker')),
]

po/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^add-po/$', views.add_po, name='add_po'),
    url(r'^edit-po/(?P<po_id>\d+)/$', views.edit_po, name='edit_po'),
    url(r'^al/(?P<po_id>\d+)/$', views.add_line, name='add_line'),
    url(r'^el/(?P<ln_id>\d+)/$', views.edit_line, name='edit_line'),
    url(r'^(?P<po_id>\d+)/$', views.po_detail, name='po_detail'),
    url(r'^by-vendor/(?P<v_id>\d+)/$', views.po_by_vendor, name='po_by_vendor'),
    url(r'^add-to-vendor/(?P<v_id>\d+)/$', views.add_po_to_vendor, name='add_po_to_vendor'),
    url(r'^$', views.po_home, name='po_home'),
]

po/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone

# Create your models here.

from vendor.models import Supplier, Publisher
from quote.models import Quote

class Cost_Center(models.Model):
    name = models.CharField(max_length=140)
    owner = models.ForeignKey(User, models.SET_NULL, null=True)
    dept_code = models.IntegerField(null=True)
    def __str__(self):
        return self.name


class PO(models.Model):
    supplier = models.ForeignKey(Supplier, models.SET_NULL, null=True)
    num = models.IntegerField(unique=True)
    issued = models.DateTimeField(null=True, blank=True)
    blanket = models.BooleanField(default=False)
    auth = models.ForeignKey(User, models.SET_NULL, null=True, blank=True)
    status = models.TextField() #make this a dropdown?
    comments = models.TextField(null=True, blank=True)
    #add tax handling
    tax = models.BooleanField(default=False)
    tax_amt = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=True)
    subtotal = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=True)
    total = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    viewed = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now, null=True, blank=True)
    quote = models.ForeignKey(Quote, models.SET_NULL, null=True, blank=True)
    budgeted = models.BooleanField(default=False)
    version = models.IntegerField(default=1)
    def __str__(self):
        return str(self.supplier.name)+str(self.num)

class Line_PO(models.Model):
    po = models.ForeignKey(PO)
    desc = models.TextField()
    item_num = models.TextField(null=True, blank=True)
    publisher = models.ForeignKey(Publisher, models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField()
    uom = models.TextField()
    unit_cost = models.DecimalField(max_digits=19, decimal_places=2)
    dept_code = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    exp_date = models.DateField(null=True, blank=True)
    cost_center = models.ForeignKey(Cost_Center, models.SET_NULL, null=True, blank=True)
    budget_code = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    viewed = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now, null=True, blank=True)
    line_total = models.DecimalField(max_digits=19, decimal_places=10, null=True, blank=True)
    def __str__(self):
        return str(self.desc)

po/forms.py
from django import forms

from .models import PO, Line_PO, Cost_Center
from vendor.models import Supplier, Publisher
from quote.models import Quote
from django.contrib.auth.models import User


class POForm(forms.Form):
    supplier = forms.ModelChoiceField(queryset=Supplier.objects.all())
    blanket = forms.BooleanField(required=False)
    auth = forms.ModelChoiceField(queryset=User.objects.all())
    status = forms.CharField(strip=True) #make this a dropdown?
    comments = forms.CharField(strip=True, required=False)
    #add tax handling
    tax = forms.BooleanField(required=False)
    tax_amt = forms.DecimalField(max_digits=5, decimal_places=5, required=False)
    quote = forms.ModelChoiceField(queryset=Quote.objects.all(), required=False)
    budgeted = forms.BooleanField()

class LineForm(forms.Form):
    desc = forms.CharField(strip=True)
    item_num = forms.CharField(strip=True, required=False)
    publisher = forms.ModelChoiceField(queryset=Publisher.objects.all(), required=False)
    quantity = forms.IntegerField()
    uom = forms.CharField(strip=True)
    unit_cost = forms.DecimalField(max_digits=19, decimal_places=2)
    start_date = forms.DateField(required=False)
    exp_date = forms.DateField(required=False)
    cost_center = forms.ModelChoiceField(queryset=Cost_Center.objects.all(), required=False)
    budget_code = forms.DecimalField(max_digits=6, decimal_places=3, required=False)

class CostCenterForm(forms.Form):
    pass


#cost_center = forms.ModelChoiceField(queryset=Cost_Center.objects.all())

po/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.
from .models import PO, Line_PO
from vendor.models import Supplier, Publisher
from .forms import POForm, LineForm

def po_home(request):
    pos = PO.objects.order_by('-viewed')
    pos = pos[:10]
    context = {'pos': pos}
    return render(request, 'po/po_home.html', context)

def po_detail(request, po_id):
    pos = PO.objects.get(id=po_id)
    lines = Line_PO.objects.filter(po=pos)
    subtotal = 0
    for ln in lines:
        subtotal = subtotal + ln.line_total
    pos.subtotal = subtotal
    try:
        pos.total = pos.tax_amt + subtotal
    except:
        pos.total = subtotal
    pos.save()
    context = {'pos': pos, 'lines':lines}
    return render(request, 'po/po_detail.html', context)

def add_po(request):
    pos = PO.objects.all().order_by('-num')
    try:
        last_po = pos[0]
        next_po = int(last_po.num) + 1
    except:
        next_po = 1
    if request.method == "POST":
        form = POForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            po = PO(
                #form fields
                supplier=data['supplier'], blanket=data['blanket'], auth=data['auth'], status=data['status'], comments=data['comments'], tax=data['tax'], tax_amt=data['tax_amt'], quote=data['quote'], budgeted=data['budgeted'],
                #auto fields
                num = next_po)
            po.save()
            return HttpResponseRedirect(reverse('po:po_home'))
    else:
        form = POForm()
    context = {'form': form, 'mode': 'add'}
    return render(request, 'po/poform.html', context)

def edit_po(request, po_id):
    if request.method == "POST":
        form = POForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            po= PO.objects.get(id=po_id)
            po.supplier = data['supplier']
            po.blanket = data['blanket']
            po.auth = data['auth']
            po.status = data['status']
            po.comments = data['comments']
            po.tax = data['tax']
            po.tax_amt = data['tax_amt']
            po.quote = data['quote']
            po.budgeted = data['budgeted']
            po.modified = timezone.now()
            po.save()
            return HttpResponseRedirect(reverse('po:po_detail', args=[po_id]))
    else:
        po = PO.objects.get(id=po_id)
        form = POForm(initial = {'supplier': po.supplier,
                                 'blanket': po.blanket,
                                 'auth': po.auth,
                                 'status': po.status,
                                 'comments': po.comments,
                                 'tax' : po.tax,
                                 'tax_amt' : po.tax_amt,
                                 'quote': po.quote,
                                 'budgeted': po.budgeted,
                                 })
    context = {'form': form, 'mode': 'edit', 'po_id': po_id}
    return render(request, 'po/poform.html', context)

def add_line(request, po_id):
    po = PO.objects.get(id=po_id)
    if request.method == "POST":
        form = LineForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            ln = Line_PO(
            po=po, desc=data['desc'], item_num=data['item_num'],
            publisher=data['publisher'], quantity=data['quantity'],
            uom=data['uom'], unit_cost=data['unit_cost'],
            start_date=data['start_date'], exp_date=data['exp_date'],
            cost_center=data['cost_center'], budget_code=data['budget_code'],
            )
            ln.line_total = ln.quantity * ln.unit_cost
            ln.save()
            return HttpResponseRedirect(reverse('po:po_detail', args=[po_id]))
    else:
        form = LineForm(initial={'po': po})
    context = {'form': form, 'mode': 'add', "po_id": po_id}
    return render(request, 'po/lineform.html', context)

def edit_line(request, ln_id):
    ln = Line_PO.objects.get(id=ln_id)
    po = ln.po
    if request.method=="POST":
        form = LineForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            ln.po=po
            ln.desc=data['desc']
            ln.publisher=data['publisher']
            ln.item_num=data['item_num']
            ln.quantity=data['quantity']
            ln.uom=data['uom']
            ln.unit_cost=data['unit_cost']
            ln.start_date=data['start_date']
            ln.exp_date=data['exp_date']
            ln.cost_center=data['cost_center']
            ln.budget_code=data['budget_code']
            ln.line_total = ln.quantity * ln.unit_cost
            ln.save()
            return HttpResponseRedirect(reverse('po:po_detail', args=[po.id]))
    else:
        ln = Line_PO.objects.get(id=ln_id)
        form = LineForm(initial={
                            'desc': ln.desc,
                            'item_num': ln.item_num,
                            'publisher': ln.publisher,
                            'quantity': ln.quantity,
                            'uom': ln.uom,
                            'unit_cost': ln.unit_cost,
                            'start_date': ln.start_date,
                            'exp_date': ln.exp_date,
                            'cost_center': ln.cost_center,
                            'budget_code': ln.budget_code,
        })

    context = {'form': form, 'mode': 'edit', 'po_id': po.id, "ln_id": ln_id}
    return render(request, 'po/lineform.html', context)

def po_by_vendor(request, v_id):
    v = Supplier.objects.get(id=v_id)
    pos = PO.objects.filter(supplier=v)
    context = {'v': v, 'pos': pos}
    return render(request, 'po/pobyvendor.html', context)

def add_po_to_vendor(request, v_id):
    v = Supplier.objects.get(id=v_id)
    pos = PO.objects.all().order_by('-num')
    try:
        last_po = pos[0]
        next_po = int(last_po.num) + 1
    except:
        next_po = 1
    if request.method == "POST":
        form = POForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            po = PO(
                #form fields
                supplier=data['supplier'], blanket=data['blanket'], auth=data['auth'], status=data['status'], comments=data['comments'], tax=data['tax'], tax_amt=data['tax_amt'], quote=data['quote'], budgeted=data['budgeted'],
                #auto fields
                num = next_po)
            po.save()
            return HttpResponseRedirect(reverse('po:po_home'))
    else:
        form = POForm(initial={'supplier': v})
    context = {'form': form, 'mode': 'add'}
    return render(request, 'po/poform.html', context)

po/templates/po/lineform.html
{% extends "tracker/topbar.html" %}
{% load bootstrap3 %}

{% block content %}
{% if mode == 'add' %}
<form class="form" action="{% url 'po:add_line' po_id %}" method="post">
{% endif %}
{% if mode == 'edit' %}
<form class="form" action="{% url 'po:edit_line' ln_id %}" method="post">
{% endif %}
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>
{% endblock content %}

po/templates/po/po_detail.html
{% extends "tracker/topbar.html" %}
{% load humanize %}

{% block content %}

<h1><a href='{% url "vendor:vendor_detail" pos.supplier.id %}'>{{ pos.supplier.name }}</a></h1>

<h1><small>
  <div class="  row">
    {% if pos.tax == True %}
      <div class="col-md-3">
    {% else %}
      <div class="col-md-6">
    {% endif %}
      PO Number: {{ pos.num }}
      </div>
    {% if pos.tax == True %}
      <div class="col-md-3">
        Subtotal: ${{ pos.subtotal|floatformat:"2"|intcomma }}
      </div>
      <div class="col-md-3">
        Tax: ${{  pos.tax_amt|floatformat:"2"|intcomma }}
      </div>
      <div class="col-md-3">
        Total: ${{ pos.total|floatformat:"2"|intcomma }}
      </div>
    {% else %}
      <div class="col-md-6">
        Total: ${{ pos.total|floatformat:"2"|intcomma }}
      </div>
    {% endif %}
  </div>
</small></h1>

<hr>

<ul class="nav nav-pills">
  <li><a href="{% url 'po:add_line' pos.id %}" class="btn btn-default">Add line <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></li>
</ul>

<hr>

<h4><small>Created: {{ pos.created }} | Modified: {{ pos.modified }} | Viewed: {{ pos.viewed }}</small></h4>

<hr>

<table class="table">
  <tr>
    <th>Description</th>
    <th>Item Number</th>
    <th>Publisher</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Quantity</th>
    <th>Unit</th>
    <th>Unit Cost</th>
    <th>Line Total</th>
    <th></th>
  </tr>
  {% for ln in lines %}
  <tr>
    <td>{{ ln.desc }}</td>
    <td>{{ ln.item_num }}</td>
    <td>{{ ln.publisher.name }}</td>
    <td>{{ ln.start_date }}</td>
    <td>{{ ln.exp_date }}</td>
    <td>{{ ln.quantity }}</td>
    <td>{{ ln.uom }}</td>
    <td>{{ ln.unit_cost|floatformat:"2"|intcomma }}</td>
    <td>${{ ln.line_total|floatformat:"2"|intcomma }}</td>
    <td><a href="{% url 'po:edit_line' ln.id %}" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
  </tr>
  {% empty %}
  <tr>
    <td>No Lines in PO</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

po/templates/po/po_home.html
{% extends "tracker/topbar.html" %}
{% load humanize %}

{% block content %}

<h1>PO Management</h1>
<p> </p>
<hr>
<ul class="nav nav-pills">
  <li><a href="{% url 'po:add_po' %}" class="btn btn-default">Add PO <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></li>
</ul>
<hr>
<h3>Recent POs</h3>
<table class="table">
  <tr>
    <th>PO</th>
    <th>Vendor</th>
    <th>Created</th>
    <th>Amount</th>
    <th></th>
  </tr>
  {% for po in pos %}
  <tr>
    <td><a href="{% url 'po:po_detail' po.id %}">{{po.num}}</a></td>
    <td><a href="{% url 'vendor:vendor_detail' po.supplier.id %}">{{po.supplier.name}}</a></td>
    <td>{{po.created}}</td>
    <td>${{po.total|floatformat:"2"|intcomma}}</td>
    <td>
      <a href="{% url 'po:edit_po' po.id %}" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
    </td>
  </tr>
  {% empty %}
  <tr>
    <td>You have not set up any POs!</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

po/templates/po/pobyvendor.html
{% extends "tracker/topbar.html" %}
{% load humanize %}

{% block content %}

<h1>{{v.name}} PO's</h1>
<p> </p>
<hr>
<ul class="nav nav-pills">
  <li><a href="{% url 'po:add_po_to_vendor' v.id %}" class="btn btn-default">Add PO <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></li>
</ul>
<hr>
<table class="table">
  <tr>
    <th>PO</th>
    <th>Vendor</th>
    <th>Created</th>
    <th>Amount</th>
    <th></th>
  </tr>
  {% for po in pos %}
  <tr>
    <td><a href="{% url 'po:po_detail' po.id %}">{{po.num}}</a></td>
    <td><a href="{% url 'vendor:vendor_detail' po.supplier.id %}">{{po.supplier.name}}</a></td>
    <td>{{po.created}}</td>
    <td>${{po.total|floatformat:"2"|intcomma}}</td>
    <td>
      <a href="{% url 'po:edit_po' po.id %}" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
    </td>
  </tr>
  {% empty %}
  <tr>
    <td>This vendor has no POs!</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

po/templates/po/poform.html
{% extends "tracker/topbar.html" %}
{% load bootstrap3 %}

{% block content %}
{% if mode == 'add' %}
<form class="form" action="{% url 'po:add_po' %}" method="post">
{% endif %}
{% if mode == 'edit' %}
<form class="form" action="{% url 'po:edit_po' po_id %}" method="post">
{% endif %}
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>
{% endblock content %}